### ISSUE TITLE
s510un i7에서도 사용이 가능할까요?

### ISSUE THREAD

**Issue by dayfly** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.3-Hackintosh#4]
안녕하세요 이번에 해킨을 시도를 했는데 
여기있는 EFI를 썼는데 다른건 작동을 하는데 
잠자기에 들어갔는데 검정색 화면으로 블랙 아웃 되는데 혹시 픽스 하는 방법 알려주시면 안될까요?

**Comment by whatnameisit** [comment]
우선 왜 그런 문제가 발생하는지 몰라서 정확한 픽스를 알려드리기는 어려울 것 같습니다.
노트북 종류가 비슷하셨던 것 같은데 정확히 어떤 모델에 어떤 사양이세요? README에 적혀있는 사양대로 알려주세요.

**Comment by dayfly** [comment]
cpu만 다릅니다 i7 -8550u 입니다 모델은 asus S510un입니다

**Comment by whatnameisit** [comment]
세부모델명 알려주세요. 예: S510UN-xxxxx

**Comment by Nevuly** [comment]
S510UN모델은 X510UA와 다소 차이점이 존재하는 모델로 기억합니다.

S510UN모델같은 경우 제 레포에 있는 해킨 EFI를 참고하시는게 나을듯 싶네요.

X510UA모델은 키보드 백라이트가 존재하지 않는 모델입니다.

**Comment by whatnameisit** [comment]
별 다른 말씀 없으셔서 Close합니다만, darkwake=10의 옵션을 넣어보세요. https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/issues/54#issuecomment-612618529

**Comment by dayfly** [comment]
감사합니다 ㅎㅎㅎ 잠자기는 darkwake = 10 이거랑 GPU이거 비활성로 해결 되었습니다 ㅎㅎ 근데 배터리가 너무 빨리 닳는건 해결 하는 방법 있을까요?

**Comment by whatnameisit** [comment]
저는 윈도우와 비교해봤을 때 큰 문제 없이 사용중이서 금방 방전된다고 생각하지는 않습니다. 3시간 정도인 것 같습니다.
https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.4-Hackintosh/issues/10
여기서도 배터리 빨리 줄어든다고 언급합니다. 배터리가 닳는 정도가 어느 정도인지 위 링크에서 알려주세요.

**Comment by dayfly** [comment]
그래서 혹시 몰라서 USBPORT 문제인거 같아서 포트 다시 잡고 해보고 있습니다 완전 충전 하고 실 사용 하는 시간 알려 드리겠습니다  답변 감사드립니다 :)

**Comment by dayfly** [comment]
질문하나 더 드려서 죄송합니다 혹시 배터리 절전에서 최대절전은 몇으로 주어야 하나요?
