### ISSUE TITLE
2가지 문제가 있습니다.

### ISSUE THREAD

**Issue by htogether** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.3-Hackintosh#5]
덕분에 잘 설치해서 사용중인 f510ua 사용자 입니다.

2가지 문제가 있네요.

1. 마이크가 작동하지 않습니다. 설정에보면 정상으로 잡혀있는데 동작하지 않네요.
2. 종료나 다시 시작이 되지 않습니다. 클로버 acpi 에서 shutdownfix 가 없어서 추가해줬는데도
될때도 있고 안되고 바탕화면에 마우스 커서만 보이고 종료되지 않을때도 있습니다.

**Comment by whatnameisit** [comment]
마이크는 동일한 코덱(CX8050)인지 확인해보시고, 맞다면 CodecCommander를 L/E에 설치하세요. 
외장그래픽이 들어 있는 모델이라면 upstream tctien342의 repo로 설치하시거나, boot-arg에 -wegnoegpu 입력해보세요. 그리고 Hibernate mode를 안 바꾸셨으면 바꾸어보세요. Hackintool Power 항목에서 진행 가능합니다.

**Comment by htogether** [comment]
CodecCommander 를 L/E 에 설치하니까 마이크는 잘 동작하네요.
사이드카 연결이 안되는데 블투문제인지 에어2가 지원 기기에서 빠진건지 구글해보면 지원된다는 분도 있고 안되는 분도 있네요. 아직 사이드카가 불안정한 건가요?
하이버 네이션은 0 으로 되어 있습니다. 외장 그래픽 없는 모델입니다.

**Comment by whatnameisit** [comment]
6+세대 인텔 그래픽이라서 지원되어야 하구요, 제가 아이패드가 없어서 잘 모르겠습니다. 블루투스나 와이파이는 제대로 작동하는지 확인해보세요. L/E에 블루투스 켁스트 설치하려면 Injector, RAM3, Repo가 필요하고, C/K/O에 설치하려면 Injector, RAM3, Data가 필요합니다. 그리고 켁스트 업데이트 안 하셨으면 다 업데이트 해보세요.
